### ISSUE TITLE
Issue with undefined function `nullthrows`

### ISSUE THREAD

**Issue by mhahn** [fredemmott/hack-router-codegen#14]
I'm trying to get a simple example of this running but I'm getting this error when I try and run it:
```
Fatal error: Call to undefined function FredEmmott\DefinitionFinder\nullthrows() in /var/www/vendor/fredemmott/definition-finder/src/consumers/ScopeConsumer.php on line 637
```

The README also mentions `IncludeInUriMap` which I don't see in https://github.com/fredemmott/hack-router anymore.

I'm trying to run:

```
<?hh

require_once(__DIR__.'/../vendor/hh_autoload.php');

use \FredEmmott\HackRouter\Codegen;

Codegen::forTree(
	__DIR__.'/../src/',
	shape(
		'controllerBase' 	=> \Controller::class,
		'router' 			=> shape(
			'abstract' 	=> false,
			'file' 		=> __DIR__.'/../src/Router.hh',
			'class' 	=> 'Router',
			'namespace' => 'Sample',
		)
	),
)->build();
```

I'm trying to build a simple example based on the examples in hack-router as well as the hhvm-user-documentation.

I pushed up my sample code if it helps: https://github.com/mhahn/hhvm-sample.

**Comment by fredemmott** [comment]
Thanks - can you file this over at https://github.com/fredemmott/definition-finder ?

Please also include which version of HHVM you are using.

That function is defined over at https://github.com/fredemmott/definition-finder/blob/master/src/utils.php

My guess is some kind of incompatibility with https://github.com/fredemmott/definition-finder/commit/8f0141b07c92f90ef4b530db51bf0f99463abf81

**Comment by fredemmott** [comment]
IncludeInUriMap is here: https://github.com/fredemmott/hack-router-codegen/blob/a2a2403c5df9c639a1bd25ba0d445f0fd9e28d85/src/interfaces/IncludeInUriMap.php

And sorry, yes, the docs are out of date; that's the main thing I want to get done before doing a non-RC release.

**Comment by fredemmott** [comment]
Also it's a bit weird that you're not getting the same error from hhvm-autoload :/

**Comment by fredemmott** [comment]
https://github.com/fredemmott/hhvm-autoload/blob/master/src/builders/ComposerImporter.php#L85 is the likely problem. Probably best thing to do is for definition-finder to add an hh_autoload.json

**Comment by fredemmott** [comment]
... and once that's done, https://github.com/fredemmott/hhvm-autoload/blob/master/src/builders/RootImporter.php#L20 also needs changing to use hh_autoload from vendor/ if that exists.

**Comment by mhahn** [comment]
Filed! Thanks for all the hack-* libs they're awesome!! I'm still parsing through them but would love to contribute where I can.

https://github.com/hhvm/user-documentation was an awesome resource but it would be great to have something like the sample app i started which has less going on with building documentation etc.

I'm going to be using this for the foundation of a couple projects so want to get it in a good state to walk people through.

**Comment by fredemmott** [comment]
https://github.com/fredemmott/definition-finder/commit/3ba10a36b48a2f298534ae497da758a9f50bc3ac

**Comment by fredemmott** [comment]
@mhan: You want definition-finder >= v1.4.3, hhvm-autoload >= v1.2.0

**Comment by mhahn** [comment]
thanks @fredemmott!
